# fly.toml app configuration file generated for discovery-remix on 2023-09-11T15:38:31-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "discovery-remix"
primary_region = "gig"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  cmd = ["start.sh"]
  entrypoint = ["sh"]
  auto_rollback = true

[build]

[[mounts]]
  source = "data"
  destination = "/data"

[[services]]
  http_checks = []
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"